const permissions = {
  doctor_create: true,
  doctor_read: true,
  doctor_update: true,
  doctor_delete: true,
  patient_create: true,
  patient_read: true,
  patient_update: true,
  patient_delete: true,
  usermanagement_create: true,
  usermanagement_read: true,
  usermanagement_update: true,
  usermanagement_delete: true,
  calender_create: true,
  calender_read: true,
  calender_update: true,
  calender_delete: true,
  dashboaed_create: true,
  dashboaed_read: true,
  dashboaed_update: true,
  dashboaed_delete: true,
  icd10_create: true,
  icd10_read: true,
  icd10_update: true,
  icd10_delete: true,
  charting_create: true,
  charting_read: true,
  charting_update: true,
  charting_delete: true,
  billing_create: true,
  billing_read: true,
  billing_update: true,
  billing_delete: true,
};

module.exports = {
  permissions,
};
